[project]
name = 'Decentralized-Manufacturing-Supply-Chain-Resilience'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.alternative-outsourcing]
path = 'contracts/alternative-outsourcing.clar'
clarity_version = 2
epoch = 2.5

[contracts.disruption-response]
path = 'contracts/disruption-response.clar'
clarity_version = 2
epoch = 2.5

[contracts.entity-verification]
path = 'contracts/entity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.inventory-buffer]
path = 'contracts/inventory-buffer.clar'
clarity_version = 2
epoch = 2.5

[contracts.risk-assesment]
path = 'contracts/risk-assesment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
